name: navigation
description: "Primer Parcial DADM 2024 1C"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  floor: ^1.4.2
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
